server:
  port: 8081

logging:
  file:
    name: ./log/sample.log
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigurationdo
  application:
    name: appointment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.30.94:3306/pe_appointment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: vide@lwd523146
  rabbitmq:
    host: 47.93.30.94
    port: 5672
    username: admin
    password: vide@lwd523146
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.30.94:8848
    stream:
      bindings:
        delayed-topic-output:
          destination: delayed-topic-demo
        delayed-topic-input:
          destination: delayed-topic-demo
          group: group-1
      rabbit:
        bindings:
          delayed-topic-input:
            consumer:
              delayed-exchange: true
          delayed-topic-output:
            producer:
              delayed-exchange: true