server:
  port: 8081

logging:
  file:
    name: ./log/sample.log
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigurationdo
  application:
    name: gf-appointment


